### ISSUE TITLE
bug: dataDisplay/NativeInput

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/native-web#109]
**Describe the bug**
Please refer https://github.com/wrappid/core/issues/318 for the entire issue

**To Reproduce**

**Expected behavior**

**Stack Trace**
The stack trace of the bug if any.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PritamIT2023** [comment]
- NativeInput fix label alignment

![Screenshot 2024-10-16 112733](https://github.com/user-attachments/assets/f72b5f13-1739-4134-b362-ec377b78a563)
