### ISSUE TITLE
enhancement: icon display menu issue

### ISSUE THREAD

**Issue by SaiHaritha-Kancherla** [wrappid/native-web#64]
to display the menu item icon by flag

**Comment by PritamIT2023** [comment]
### When left drawer menu is in mini-drawer state then a bracket is coming


![Screenshot 2024-06-05 at 12 37 23 PM](https://github.com/wrappid/native-web/assets/89157406/0c313bb4-e700-49c1-9e87-332d7b794ab4)

**Comment by techoneel** [comment]
This issue is resolved with https://github.com/wrappid/native-web/issues/71 by @PritamIT2023.

Closing this issue since it's resolved.
