### ISSUE TITLE
enhancement: NativeImagePicker Icon update

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/native-web#70]
**Description**
NativeImagePicker currently uses "photo_camera" mui icon.   
"upload" mui icon is more suitable

**Comment by techoneel** [comment]
@anantakumarghosh please give an update on the issue.

**Comment by anantakumarghosh** [comment]
> @anantakumarghosh please give an update on the issue.
This issue is resolved by 5383c0e

**Comment by anantakumarghosh** [comment]
> > @anantakumarghosh please give an update on the issue.
> > This issue is resolved by [5383c0e](https://github.com/wrappid/native-web/commit/5383c0eba50c167077ffcd1fb4ad3f8acd4831da)


Hence closing
